### Create text(1)
POST http://localhost:8080/text/hello
Content-Type: text/plain

Hello, World!

### Create text(2)
POST http://localhost:8080/text/name
Content-Type: text/plain

My name is 'text'

### List all text
GET http://localhost:8080/textall

### Delete selected text
DELETE http://localhost:8080/text/hello

### Get selected text (failed)
GET http://localhost:8080/text/hello

### Get selected text (success)
GET http://localhost:8080/text/name

